name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: pip install -U pip
      - run: pip3 install pytest
      - run: pip3 install coverage
      - run: pip3 install pytest-cov
      - run: python3 -m pytest --cov --cov-branch -v