name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      run: |
        pwd
        ls -l
        pip install -U pip
        pip install -r ../requirements.txt
        python3 -m pytest --cov --cov-branch -v