name: check pip
on: push

jobs:
  build:
    name: piplist
    runs-on: ubuntu-latest
    steps:
      - name: before pip list
        run: pip list
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: after action pip list
        run: pip list
