# name: Hello, World!
# on: push

# jobs:
#   build:
#     name: Greeting
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-python@v4
#         with:
#           python-version: '3.10'  # 使用するPythonのバージョンを指定  
#       - run: |
#           pwd
#       - run: |
#           ls -l
#       - run: |
#           sudo apt install -y tree
#           tree . -a
#       - run: pip install -U pip
#       - run: pip3 install coverage
#       - run: pip3 install pytest-cov
#       - run: python3 -m pytest --cov --cov-branch -v
name: Pytest cov html
on: push

jobs:
  build:
    name: testing
    runs-on: ubuntu-latest
    steps:
      # リポジトリへのアクセスとpythonのバージョンを指定
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用するPythonのバージョンを指定  
      - name: setup pip
          run: |
            pip install -U pip
            pip3 install coverage
            pip3 install pytest-cov
      - name: starttest
          run: python3 -m pytest --cov --cov-branch --cov-report=html -v 
      #--htmlcovディレクトリができているはずなので.zipにしてアーティファクトに上げます。
      - uses: actions/upload-artifact@v3
        with:
          name: htmlcovzip
          path: htmlcov
          #↑作成されるzipファイルは名前がhtmlcovzip.zip