name: check pip
on: push

jobs:
  build:
    name: piplist
    runs-on: ubuntu-latest
    steps:
      - run: pip install -U pip
      - run: pip install pytest
      - run: pip list
      - run: pip3 list
