name: check pip
on: push

jobs:
  build:
    name: piplist
    runs-on: ubuntu-latest
    steps:
      - run: pip install -U pip
      - run: pip install pytest
      - run: pip list
      - uses: actions/checkout@v3
      - run: |
          mkdir artfiactpip
          pip freeze > artfiactpip/freezed.txt
      # - run: mkdir artfiactpip
      # - run: pip freeze > artfiactpip/freezed.txt
      - uses: actions/upload-artifact@v2
        with:
          name: artfiactpip
          path: artfiactpip
