name: check pip
on: push

jobs:
  build:
    name: piplist
    runs-on: ubuntu-latest
    steps:
      - run: pip install -U pip
      - run: pip install pytest
      - run: pip list
      - uses: actions/checkout@v3
      #--以下のrunの中は2つのrunの行にするとエラーになります。--
      #- run: |
      #   mkdir artifactpip
      #   pip freeze > artifactpip/freezed.txt
      - run: mkdir artifactpip
      - run: pip freeze > artifactpip/freezed.txt
      - uses: actions/upload-artifact@v2
        with:
          name: artifactpip
          path: artifactpip
