name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
       #↓以下を書き換えています。
       #runは上から順番に実行されます。
      - run: python3 --version
      - run: |
          pwd
          ls -l
          : # コメントアウトの仕方です。
      - run: |
          pwd
          ls -l
      - run: pwd
      - run: ls -l
      - run: sudo apt install -y tree
      - run: tree . -a
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 使用するPythonのバージョンを指定
      - run: python3 --version
      - run: pip3 list
