name: check pip
on: push

jobs:
  build:
    name: piplist
    runs-on: ubuntu-latest
    steps:
      - run: pip install -U pip
      - run: pip install pytest
      - run: pip list
      - run: pip freeze > aritifact_pip/freezed.txt
      - uses: actions/upload-artifact@v2
        with:
          name: aritifact_pip
          path: aritifact_pip
